FROM ubuntu

MAINTAINER Shailesh Wadhwa

# Add and Run

RUN apt-get update \
	&& apt-get install -y python3 python3-pip \
	&& pip3 install jupyter \
	&& pip3 install Pillow \
	&& apt-get clean

# PERSISTENCE
VOLUME ["/notebooks"]

# WORKDIR

WORKDIR /notebooks

# COMMAND AND ENTRY-POINT
CMD ["jupyter", "notebook", "--allow-root", "--ip=0.0.0.0", "--port=9000"]

# NETOWRK
EXPOSE 9000
 
